Add cards component and basic styling
oy-gen/capstone-project pull request #2
Opened 2022-05-23 14:49 UTC by oy-gen

2022-05-23 16:20 UTC, aclaes requested changes

2022-05-23 16:20 UTC, alexclaes commented on components/RoundNumberToTwo
> +export default function RoundNumberToTwo(x) {
I think there is no reason to create a separated function for this functionality. It’s way simpler to just call `toPrecision(4)` wherever needed.

If you really want to keep this file: Please don't forget to add the extension `.js` to the file name.
This file doesn't represent a component and should not be placed in the `components` directory. Consider moving it to the `lib` directory.

2022-05-23 16:20 UTC, aclaes commented on pages/_app.js
> +   _outline: 1px solid #7E7E7E;
I think this line can be removed

2022-05-24 09:42 UTC, marcbendixen approved these changes
Good job
LGTM 🚀

2022-05-24 09:52 UTC, merged